######################################################################
# Automatically generated by qmake (3.1) Tue Mar 11 17:24:47 2025
######################################################################

QT+=core widgets
TEMPLATE = app
TARGET = screen_watermark
CONFIG +=   c++17 \
            release \

# tmp dir
DESTDIR = $$PWD/build/release
MOC_DIR = $$PWD/build/moc
RCC_DIR = $$PWD/build/rcc
UI_DIR = $$PWD/build/ui
OBJECTS_DIR = $$PWD/build/obj

# resource
#RESOURCES += dataspyresult.qrc

win32:{
    message(This is windows system.)
}
linux {
    message(This is linux system.)
    
    HEADERS += CTextWatermark.h

    SOURCES += main.cpp \
        CTextWatermark.cpp
}
